Small UI Fix To Update ComboBox To Display Selection
openrocket/openrocket pull request #1367
Opened 2022-05-21 16:40 UTC by RemingtonHolder

Small UI fix to update the ComboBox to display the selected item in: Preferences --> Simulation --> Simulation Options --> Geodetic Calculations

2022-05-23 21:08 UTC, JoePfeiffer commented
I know it's a one-liner, but I'm having a little trouble understanding -- unless I'm misreading, this is setting the selected item to the already-selected item, so it should already be displaying it.  Are there conditions under which it isn't?

2022-05-24 10:37 UTC, RemingtonHolder commented
When I was using the newest OR release for some reason it was not visually updating whenever you changed the value, it may just be a one off bug on my machine but this one liner fixed it.

2022-05-26 11:37 UTC, SiboVG commented
I'm also not experiencing this issue, so must be a one off.

I would however suggest trying `gcsCombo.repaint()`, does that also solve the issue? And at a comment next to it stating why that line is added, e.g. `gcsCombo.repaint()    // On some machines, the combobox did not visually update to the selected item`

2022-05-29 17:03 UTC, SiboVG requested changes

2022-05-29 17:03 UTC, SiboVG commented on swing/src/net/sf/openrocket/gui/dialogs/preferences/SimulationPreferencesPanel.java
> +				gcsCombo.setSelectedItem(gcsCombo.getSelectedItem());
Replace by `gcsCombo.repaint() // On some machines, the combobox did not visually update to the selected item`

2022-05-29 17:51 UTC, merged