Fixed NPE when scaling when no components are selected
openrocket/openrocket pull request #1716
Opened 2022-10-03 00:22 UTC by raynichc

Fixes #1713, NPE was thrown when no components were selected and Edit > Scale was used to scale the rocket. This seems to be because `DocumentSelectionModel.getSelectedComponents` returns null if no components are selected, as opposed to an empty list.

2022-10-04 08:36 UTC, SiboVG requested changes

2022-10-04 18:00 UTC, SiboVG commented
Looking back at it, I'm not entirely convinced with this change, since there are instances in OR that check whether `getSelectedComponents` returns null. We can still use the solution of this PR, but then we'd have to replace all the null-checking code with code checking for a zero-sized collection.

2022-10-04 18:00 UTC, SiboVG approved these changes

2022-10-05 00:10 UTC, raynichc commented
I'll have a look into it later today, but its probably better that a zero-sized collection be returned and handled, as opposed to having to check for null first.

2022-10-05 03:52 UTC, JoePfeiffer commented
> I'll have a look into it later today, but its probably better that a zero-sized collection be returned and handled, as opposed to having to check for null first.

Yes, but making fewer changes to the code this close to release trumps it.

2022-10-06 01:47 UTC, merged