Release notes for 24.12b1
openrocket/openrocket pull request #2602
Opened 2024-12-02 01:54 UTC by neilweinstock

2024-12-02 01:59 UTC, SiboVG requested changes

2024-12-02 01:59 UTC, SiboVG commented on ReleaseNotes.md
> +<div id="24.12">
change to 24.12.beta.01

2024-12-02 01:59 UTC, SiboVG commented on ReleaseNotes.md
> +## OpenRocket 24.12 beta 1
Use the same formatting as the other releases:
```
OpenRocket 24.12.beta.01 (2024-12-XX)
-----------------------------------------
```

2024-12-02 02:00 UTC, SiboVG commented on ReleaseNotes.md
> +* **Switched build system from And to Gradle**
Ant*

2024-12-02 02:02 UTC, SiboVG commented on ReleaseNotes.md
> +
Also add "Clamp compressibility correction factor to avoid singularity (#2570)"?

2024-12-02 02:03 UTC, SiboVG commented
Thanks @neilweinstock! Always fun to see an overview of all the changes :)

2024-12-02 02:09 UTC, neilweinstock commented
All changes made, thanks for the quick review!

2024-12-02 02:11 UTC, neilweinstock commented
> Thanks @neilweinstock! Always fun to see an overview of all the changes :)

It's quite a lot!

2024-12-02 12:09 UTC, SiboVG commented on ReleaseNotes.md
> +* Clamp compressibility correction factor to avoid singularity (fixes 2570)
2570 is the ID of the PR, there is no issue related to it.

2024-12-02 14:02 UTC, SiboVG approved these changes

2024-12-02 14:05 UTC, neilweinstock commented
We have to wait to fill in the release date, right?  I can't remember if we put dates on the beta releases.

2024-12-02 15:53 UTC, JoePfeiffer commented on ReleaseNotes.md
> +* **Add SIM_ABORT flight even type, instead of throwing exceptions**
even -> event

2024-12-02 15:54 UTC, JoePfeiffer commented on ReleaseNotes.md
> +* Don't set open airframe warning if rocket is unstable (and improve wording)
Don't set open airframe warning on booster stages if either they're about to deploy a recovery device or they're unstable.

2024-12-03 21:17 UTC, JoePfeiffer approved these changes

2024-12-04 13:12 UTC, merged